### ISSUE TITLE
Release 7.0

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1570]
This issue collects things to be done for a 7.0.0 release.

- [x] Remove the "not finalized" in the schema messages docs: https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/schema/messages.md#widget-messaging-protocol-version-2-not-finalized (#1577)
- [x] Generate the model attributes and update them in the schema package (#1577)
- [x] Take a pass through the docs (#1578)
- [x] Run through Changelog one last time (#1579)
- [x] Release 7.0.0rc0
- [x] Prepare release announcement, including various stats, etc. (#1580, #1584)
- [x] Post to mailing list about RC, ask for testers
- [x] Announce RC in the dev meeting on Tuesday
- [x] On release, bump the pre-1.0 js packages to 1.0.

**Comment by stonebig** [comment]
Don't you want to add a list of classic external widgets that do work (work not) in both classical and Lab mode ? (so that enthousiast users do know in advance if they are going to blow up (or not) their environnement by upgrading)

currently there is a know regression on ipyleaflet at least.

**Comment by SylvainCorlay** [comment]
@stonebig there is really a lot of those downstream projects. It is not very surprising that some will need some time to upgrade when 7.0 is out. I don't think that it is really manageable to track all downstream projects from ipywidgets and check that they already work with the beta.

**Comment by jasongrout** [comment]
At this point, @maartenbreddels, @vidartf, @SylvainCorlay, @mwcraig - does anyone have any objection to releasing an RC?

**Comment by jasongrout** [comment]
Just posted rc0

**Comment by jasongrout** [comment]
Sample release notes, as of right now:

It has been 168 days since the last release. In this release, we closed [137 issues](https://github.com/jupyter-widgets/ipywidgets/issues?q=is%3Aissue+is%3Aclosed+milestone%3A7.0) and [251 pull requests](https://github.com/jupyter-widgets/ipywidgets/pulls?q=is%3Apr+milestone%3A7.0+is%3Aclosed) with [1207](https://github.com/jupyter-widgets/ipywidgets/compare/6.0.0...7.0.0) commits, of which 954 are not merges.

We'd like to thank the following 19 individuals who submitted a code commit to the 7.0 release, and especially congratulate the 13 new contributors.

* Benjamin Ragan-Kelley
* Charnpreet Singh (new contributor)
* Dave Hirschfeld
* Fermi Paradox (new contributor)
* Jan Lübbe (new contributor)
* Janki Akhani (new contributor)
* Jason Grout
* Kiko Correoso (new contributor)
* Luke Zoltan Kelley (new contributor)
* Maarten Breddels
* Maksim Noy (new contributor)
* Matthew Craig
* Nick Fernandez (new contributor)
* Pascal Bugnion (new contributor)
* Ribamar Santarosa (new contributor)
* Rick Teachey (new contributor)
* Scott Sievert (new contributor)
* Sylvain Corlay
* Vidar Tonaas Fauske (new contributor)

**Comment by jasongrout** [comment]
We've released! I'll close this issue, and post the release notes as a comment.

**Comment by jasongrout** [comment]
Updated release notes:

It has been 171 days since the last release. In this release, we closed [142 issues](https://github.com/jupyter-widgets/ipywidgets/issues?q=is%3Aissue+is%3Aclosed+milestone%3A7.0) with [259 pull requests](https://github.com/jupyter-widgets/ipywidgets/pulls?q=is%3Apr+milestone%3A7.0+is%3Aclosed). We had 989 non-merge commits and 261 merges, for a total of [1250](https://github.com/jupyter-widgets/ipywidgets/compare/6.0.0...7.0.0) total commits.

We'd like to thank the following 19 individuals (listed in alphabetical order) who submitted a commit to the 7.0 release, and we especially congratulate the 13 new contributors.

* Benjamin Ragan-Kelley
* Charnpreet Singh (new contributor)
* Dave Hirschfeld
* Fermi Paradox (new contributor)
* Jan Lübbe (new contributor)
* Janki Akhani (new contributor)
* Jason Grout
* Kiko Correoso (new contributor)
* Luke Zoltan Kelley (new contributor)
* Maarten Breddels
* Maksim Noy (new contributor)
* Matthew Craig
* Nick Fernandez (new contributor)
* Pascal Bugnion (new contributor)
* Ribamar Santarosa (new contributor)
* Rick Teachey (new contributor)
* Scott Sievert (new contributor)
* Sylvain Corlay
* Vidar Tonaas Fauske (new contributor)
