### ISSUE TITLE
Port 7.x branch changes to master

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#3085]
When the 8.0 release stalled, we continued to work on the 7.x branch and release minor releases of 7.x. Consequently, there are a number of changes in the 7.x branch that should be ported to master. This issue tracks that work.

## PRs in 7.x not on master

This is a checklist of PRs merged, with the oldest at the top.

% git log master..7.x --merges --oneline | tail -r
- [x] 4b1dff6e Merge pull request #2781 from jasongrout/w7jlab2
- [x] 0f75c9fe Merge pull request #2793 from jasongrout/fontawesome: ported in #2816
- [x] c138c0f9 Merge pull request #2803 from jasongrout/jlab2: not necessary
- [x] 476cb915 Merge pull request #2804 from jasongrout/fontcolor: this is a backport of #2801
- [ ] c38ed09e Merge pull request #2973 from jasongrout/jlab3
- [ ] bd3b2e91 Merge pull request #2974 from jasongrout/release
- [ ] a6ebd34e Merge pull request #2990 from jasongrout/packaging
- [ ] 019256d5 Merge pull request #2991 from jasongrout/packaging
- [ ] 567108ba Merge pull request #2992 from jasongrout/upjlab
- [ ] 5754418e Merge pull request #2993 from jasongrout/license
- [ ] 5bb6573f Merge pull request #2995 from martinRenou/remove_jlab_dependency
- [ ] 24fe9e6e Merge pull request #3044 from jasongrout/jlab3
- [ ] f52839d4 Merge pull request #3008 from martinRenou/jupyterlab_widgets_dependency
- [ ] d6890851 Merge pull request #3045 from jasongrout/jlab3-2
- [ ] 249a7cc0 Merge pull request #3046 from jasongrout/ch2
- [ ] c25d3cc6 Merge pull request #3047 from jasongrout/updatewidget
- [ ] e7fa45cb Merge pull request #3050 from jasongrout/py2
- [ ] e15debb8 Merge pull request #3051 from jasongrout/update
- [x] a4bd5dfc Merge pull request #3014 from ianhi/7.x: see https://github.com/jupyter-widgets/ipywidgets/issues/3085#issuecomment-772929911
- [ ] 4e94892c Merge pull request #3059 from patviafore-canonical/7.x

I also noticed that commit 32d2a7b758b12c631b3356fb0c7d50f8d4646a53 was on 7.x.

**Comment by ianhi** [comment]
>  a4bd5df Merge pull request #3014 from ianhi/7.x

is already on master. I made two PRs one for 7.x and one for master

**Comment by jasongrout** [comment]
The remaining PRs all have to do with support JupyterLab 3.0. So instead of trying to merge them one by one, I'm first trying a wholesale merge of 7.x into master.
